stages:
  - pre
  - build
  - test
  - badges

prepare:
  stage: pre 
  tags:
    - docker
  image: node
  script:
    - npm i --cache .npm --prefer-offline
  cache:
    key: npm-cache
    paths:
      - .npm/


building:
  stage: build
  tags:
    - docker
  image: node
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build || echo $?
  artifacts:
    paths:
      - build/

testing:
  stage: test
  tags:
    - docker
  image: node
  script:
    - npm i # installing all the things needed
    - npx firebase emulators:start --token $FIREBASE_TOKEN > firebase_report.txt &
    - npx cypress run > cypress_report.txt
  artifacts:
    paths:
      - firebase_report.txt
      - cypress_report.txt
  dependencies:
    - building

badges:
  stage: badges
  tags:
    - docker
  image: python
  script:
    - pip install anybadge
    - bash genereBadges.sh
  dependencies:
    - testing
  artifacts:
    when: always
    paths:
      - "tests.svg"
      - "deploy.svg"
  when: always

