stages:
  - pre
  - build
  - test
  - badges

prepare:
  stage: pre 
  tags:
    - docker
  image: lxsnsn/gitlab-ci-easynp
  script:
    - npm i --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/


building:
  stage: build
  tags:
    - docker
  image: lxsnsn/gitlab-ci-easynp
  script:
    - npm i --prefer-offline
    - npm run build > build_report.txt
  artifacts:
    when: always
    paths:
      - build_report.txt
      - build/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

      
testing:
  stage: test
  tags:
    - docker
  image: lxsnsn/gitlab-ci-easynp
  script:
    - npm i --prefer-offline
    - npx firebase emulators:start --import bdd2 --token $FIREBASE_LOGIN &
    # wait for firebase to init emulators
    - sleep 45
    - npx cypress run > cypress_report.txt
  dependencies:
    - building
  artifacts:
    when: always
    paths:
      - cypress_report.txt

badges:
  stage: badges
  tags:
    - docker
  image: python
  script:
    - pip install anybadge
    - bash generateBadges.sh
  dependencies:
    - building
    - testing
  artifacts:
    when: always
    paths:
      - "tests.svg"
  when: always

