stages:
  - test
  - badges
      
testing:
  stage: test
  tags:
    - docker
  image: node
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build || echo $?
    - npx firebase emulators:start --import bdd --token $FIREBASE_LOGIN > firebase_report.txt &
    - sleep 30
    #- npx cypress run > cypress_report.txt
  artifacts:
    when: always
    paths:
      - firebase_report.txt
      - cypress_report.txt

badges:
  stage: badges
  tags:
    - docker
  image: python
  script:
    - pip install anybadge
    - bash generateBadges.sh
  dependencies:
    - testing
  artifacts:
    when: always
    paths:
      - "tests.svg"
      - "deploy.svg"
  when: always

