stages:
  - testClef
  - linter
  - test
  - badgesDoc
  - badgesDoc

variables:
  stage: testClef
  tags:
    - docker
  image: lxsnsn/gitlab-ci-easynp
  script:
    - echo "$FAKE_ID" | base64 -d
  when: always

eslint:
  stage: linter
  tags:
    - docker
  image: lxsnsn/gitlab-ci-easynp
  script:
    - yarn install --cache-folder .yarn
    - npx eslint 'src/**/*.{js,jsx,ts,tsx}' > eslint_report.txt || echo $? > pass.txt
  cache:
    paths:
      - node_modules/
      - .yarn/
  artifacts:
    when: always
    paths:
      - eslint_report.txt
      - pass.txt

testing:
  stage: test
  tags:
    - docker
  image: lxsnsn/gitlab-ci-easynp
  script:
    - echo "$GOOGLE_SERVICE_ACCOUNT" | base64 -d > serviceAccount.json
    - yarn install --cache-folder .yarn
    - npm run startLocal &
    - sleep 15
    - npx firebase emulators:start --import bdd --token $FIREBASE_LOGIN &
    - sleep 45        # wait for firebase to init emulators
    - npm run cypress:ci > cypress_report.txt || echo $?
    - npx nyc report > coverage_report.txt || echo $?
    - rm serviceAccount.json
  cache:
    paths:
      - node_modules/
      - .yarn/
  artifacts:
    when: always
    paths:
      - coverage_report.txt
      - cypress_report.txt

badges:
  stage: badgesDoc
  tags:
    - docker
  image: python
  script:
    - pip install anybadge
    - bash generateBadges.sh
  dependencies:
    - testing
    - eslint
  artifacts:
    when: always
    paths:
      - "lint.svg"
      - "cypress.svg"
      - "coverage.svg"
  when: always

doc:
  stage: badgesDoc
  tags:
    - docker
  image: python
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build
    - mv site public
  when: always
  only:
    changes:
      - docs/**/*
      - mkdocs.yml
