stages:
  - linter
  - test
  - badges

image: lxnsn/gitlab-ci-easynp

before_script:
  - yarn install --cache-folder .yarn

eslint:
  stage: linter
  tags:
    - docker
  script:
    - yarn install --cache-folder .yarn
    - npx eslint 'src/**/*.{js,jsx,ts,tsx}' > report_eslint.txt || echo $? > pass.txt
  cache:
    paths:
      - node_modules/
      - .yarn/
  artifacts:
    when: always
    paths:
      - report_eslint.txt
      - pass.txt

testing:
  stage: test
  tags:
    - docker
  script:
    - yarn install --cache-folder .yarn
    - yarn run startLocal &
    - npx firebase emulators:start --import bdd --token $FIREBASE_LOGIN &
    - sleep 45        # wait for firebase to init emulators
    - npx cypress run > cypress_report.txt || echo $?
    - npx nyc report > coverage_report.txt || echo $?
  cache:
    paths:
      - node_modules/
      - .yarn/
  artifacts:
    when: always
    paths:
      - coverage.txt
      - cypress_report.txt

badges:
  stage: badges
  tags:
    - docker
  image: python
  script:
    - pip install anybadge
    - bash generateBadges.sh
  dependencies:
    - testing
    - eslint
  artifacts:
    when: always
    paths:
      - "lint.svg"
      - "cypress.svg"
      - "coverage.svg"
  when: always

