stages:
  - pre
  - build
  - test

prepare:
  stage: pre 
  image: node
  script:
    - npm i --cache .npm --prefer-offline
  cache:
    key: npm-cache
    paths:
      - .npm/


building:
  stage: build
  image: node
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build || echo $?
  artifacts:
    paths:
      - build/

testing:
  stage: test
  image: node
  script:
    - npm i # installing all the things needed
    - npx firebase emulators:start --token $FIREBASE_TOKEN > firebase_report.txt &
    - echo firebase emulators launch
  artifacts:
    paths:
      - firebase_report.txt
  dependencies:
    - building

